### ISSUE TITLE
Crashes when reading emojis

### ISSUE THREAD

**Issue by weinholt** [ktakashi/json-tools#1]
Hello Takashi!

\uNNNN escapes in JSON are in UTF-16, but interpret-string-unicode-escape passes them to integer->char. A demonstration:

```Scheme
> (string->utf16 "😺")
#vu8(#xD8 #x3D #xDE #x3A)
```

In Node this gives back the emoji:

```JavaScript
> "\uD83D\uDE3A"
'😺'
```

And with json-tools it crashes:

```Scheme
> (print-radix 16)
> (json-read (open-string-input-port "\"\\uD83D\\uDE3A\""))
Exception in integer->char: #xD83D is not a valid unicode scalar value
Type (debug) to enter the debugger.
```

**Comment by ktakashi** [comment]
Thank you for the report!
I might be lazy to implement unicode scalar at that moment. I'll check.

**Comment by ktakashi** [comment]
Okay, the `(json)` library was just ported from Chicken's egg without any feature modification except applying R6RS. And it doesn't support unicode scalar. I'll support it shortly.

**Comment by weinholt** [comment]
Thanks, it works!
